### ISSUE TITLE
Auth error [Cannot read property '0' of undefined]

### ISSUE THREAD

**Issue by shrekmaster** [endoplasmic/google-assistant#106]
Trying to execute the code with client_secret json file. When I put the path in the code and try to execute after installing node module, get the following error

`/google-assistant/components/auth.js:26
  const oauthClient = new OAuth2Client(key.client_id, key.client_secret, key.redirect_uris[0]);
                                                                                                                                           ^

TypeError: Cannot read property '0' of undefined
    at new Auth (/google-assistant/components/auth.js:26:91)
    at new GoogleAssistant (/google-assistant/index.js:33:18)
    at Object.<anonymous> (/google-assistant/examples/console-input.js:60:19)
`

Any idea what I may be doin wrong here? client secret json file created and authenticated. It also works fine with another code that I have tried before

**Comment by apop880** [comment]
I had to add "redirect_uris": ["https://localhost:3000"] to the "installed" section of my key JSON file. The URI itself doesn't really matter, but if you put it at localhost, it doesn't check for validity. I'd pick a port where you don't currently have something running. Then, when you get redirected, no page will load, but you just need to copy the code section of the URI from your address bar and paste that in to complete authentication.
