### ISSUE TITLE
Not working on mac

### ISSUE THREAD

**Issue by sipvoip** [endoplasmic/google-assistant#21]
Nathans-Mac:google-assistant nathan$ node examples/mic-speaker.js 
Say something!
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn rec ENOENT
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

Nathans-Mac:google-assistant nathan$ node examples/console-input.js 
Type your request: Hello
Fetching TTS file...
Conversation Error: { AssertionError
    at new goog.asserts.AssertionError (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:98:603)
    at Object.goog.asserts.fail (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:100:89)
    at Object.jspb.utils.byteSourceToUint8Array (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:247:257)
    at jspb.BinaryWriter.writeBytes (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:285:83)
    at Function.proto.google.assistant.embedded.v1alpha1.ConverseRequest.serializeBinaryToWriter (/Users/nathan/google-assistant/lib/google/assistant/embedded/v1alpha1/embedded_assistant_pb.js:1417:12)
    at proto.google.assistant.embedded.v1alpha1.ConverseRequest.serializeBinary (/Users/nathan/google-assistant/lib/google/assistant/embedded/v1alpha1/embedded_assistant_pb.js:1394:60)
    at requestSerialize (/Users/nathan/google-assistant/components/embedded-assistant.js:10:27)
    at ClientDuplexStream.serialize (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/common.js:53:12)
    at ClientDuplexStream._write (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/client.js:158:20)
    at doWrite (_stream_writable.js:385:12)
  message: 'Failure: Type not convertible to Uint8Array.',
  reportErrorToServer: true,
  messagePattern: 'Failure: Type not convertible to Uint8Array.' }
Conversation Error: { AssertionError
    at new goog.asserts.AssertionError (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:98:603)
    at Object.goog.asserts.fail (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:100:89)
    at Object.jspb.utils.byteSourceToUint8Array (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:247:257)
    at jspb.BinaryWriter.writeBytes (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:285:83)
    at Function.proto.google.assistant.embedded.v1alpha1.ConverseRequest.serializeBinaryToWriter (/Users/nathan/google-assistant/lib/google/assistant/embedded/v1alpha1/embedded_assistant_pb.js:1417:12)
    at proto.google.assistant.embedded.v1alpha1.ConverseRequest.serializeBinary (/Users/nathan/google-assistant/lib/google/assistant/embedded/v1alpha1/embedded_assistant_pb.js:1394:60)
    at requestSerialize (/Users/nathan/google-assistant/components/embedded-assistant.js:10:27)
    at ClientDuplexStream.serialize (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/common.js:53:12)
    at ClientDuplexStream._write (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/client.js:158:20)
    at doWrite (_stream_writable.js:385:12)
  message: 'Failure: Type not convertible to Uint8Array.',
  reportErrorToServer: true,
  messagePattern: 'Failure: Type not convertible to Uint8Array.' }
Conversation Error: { AssertionError
    at new goog.asserts.AssertionError (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:98:603)
    at Object.goog.asserts.fail (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:100:89)
    at Object.jspb.utils.byteSourceToUint8Array (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:247:257)
    at jspb.BinaryWriter.writeBytes (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:285:83)
    at Function.proto.google.assistant.embedded.v1alpha1.ConverseRequest.serializeBinaryToWriter (/Users/nathan/google-assistant/lib/google/assistant/embedded/v1alpha1/embedded_assistant_pb.js:1417:12)
    at proto.google.assistant.embedded.v1alpha1.ConverseRequest.serializeBinary (/Users/nathan/google-assistant/lib/google/assistant/embedded/v1alpha1/embedded_assistant_pb.js:1394:60)
    at requestSerialize (/Users/nathan/google-assistant/components/embedded-assistant.js:10:27)
    at ClientDuplexStream.serialize (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/common.js:53:12)
    at ClientDuplexStream._write (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/client.js:158:20)
    at doWrite (_stream_writable.js:385:12)
  message: 'Failure: Type not convertible to Uint8Array.',
  reportErrorToServer: true,
  messagePattern: 'Failure: Type not convertible to Uint8Array.' }
Conversation Error: { Error: Serialization failure
    at ClientDuplexStream._emitStatusIfDone (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/client.js:270:19)
    at ClientDuplexStream._receiveStatus (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/client.js:248:8)
    at /Users/nathan/google-assistant/node_modules/grpc/src/node/src/client.js:772:12 code: 13, metadata: Metadata { _internal_repr: {} } }

**Comment by endoplasmic** [comment]
What is the output of `node -v` and `npm -v`?

Also for the first error, you need to make sure you've installed SoX (scroll down a little bit on the README and you'll see the links to the modules that have prerequisites).

**Comment by sipvoip** [comment]
After installing SoX I get the same errors with both examples. 

brew installed node 8 by default, but I also tried 6.

Nathans-Mac:google-assistant nathan$ node -v
v6.11.2
Nathans-Mac:google-assistant nathan$ npm -v
5.3.0


Nathans-Mac:google-assistant nathan$ node examples/mic-speaker.js 
Say something!
Conversation Error: { AssertionError: Failure: Type not convertible to Uint8Array.
    at new goog.asserts.AssertionError (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:98:603)
    at Object.goog.asserts.fail (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:100:89)
    at Object.jspb.utils.byteSourceToUint8Array (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:247:257)
    at jspb.BinaryWriter.writeBytes (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:285:83)
    at Function.proto.google.assistant.embedded.v1alpha1.ConverseRequest.serializeBinaryToWriter (/Users/nathan/google-assistant/lib/google/assistant/embedded/v1alpha1/embedded_assistant_pb.js:1417:12)
    at proto.google.assistant.embedded.v1alpha1.ConverseRequest.serializeBinary (/Users/nathan/google-assistant/lib/google/assistant/embedded/v1alpha1/embedded_assistant_pb.js:1394:60)
    at requestSerialize (/Users/nathan/google-assistant/components/embedded-assistant.js:10:27)
    at ClientDuplexStream.serialize (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/common.js:53:12)
    at ClientDuplexStream._write (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/client.js:158:20)
    at doWrite (_stream_writable.js:331:12)
  message: 'Failure: Type not convertible to Uint8Array.',
  reportErrorToServer: true,
  messagePattern: 'Failure: Type not convertible to Uint8Array.' }
Conversation Error: { Error: Serialization failure
    at ClientDuplexStream._emitStatusIfDone (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/client.js:270:19)
    at ClientDuplexStream._receiveStatus (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/client.js:248:8)
    at /Users/nathan/google-assistant/node_modules/grpc/src/node/src/client.js:772:12 code: 13, metadata: Metadata { _internal_repr: {} } }
Conversation Error: { AssertionError: Failure: Type not convertible to Uint8Array.
    at new goog.asserts.AssertionError (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:98:603)
    at Object.goog.asserts.fail (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:100:89)
    at Object.jspb.utils.byteSourceToUint8Array (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:247:257)
    at jspb.BinaryWriter.writeBytes (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:285:83)
    at Function.proto.google.assistant.embedded.v1alpha1.ConverseRequest.serializeBinaryToWriter (/Users/nathan/google-assistant/lib/google/assistant/embedded/v1alpha1/embedded_assistant_pb.js:1417:12)
    at proto.google.assistant.embedded.v1alpha1.ConverseRequest.serializeBinary (/Users/nathan/google-assistant/lib/google/assistant/embedded/v1alpha1/embedded_assistant_pb.js:1394:60)
    at requestSerialize (/Users/nathan/google-assistant/components/embedded-assistant.js:10:27)
    at ClientDuplexStream.serialize (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/common.js:53:12)
    at ClientDuplexStream._write (/Users/nathan/google-assistant/node_modules/grpc/src/node/src/client.js:158:20)
    at doWrite (_stream_writable.js:331:12)
  message: 'Failure: Type not convertible to Uint8Array.',
  reportErrorToServer: true,
  messagePattern: 'Failure: Type not convertible to Uint8Array.' }
Conversation Error: { AssertionError: Failure: Type not convertible to Uint8Array.
    at new goog.asserts.AssertionError (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:98:603)
    at Object.goog.asserts.fail (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:100:89)
    at Object.jspb.utils.byteSourceToUint8Array (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:247:257)
    at jspb.BinaryWriter.writeBytes (/Users/nathan/google-assistant/node_modules/google-protobuf/google-protobuf.js:285:83)
    at Function.proto.google.assistant.embedded.v1alpha1.ConverseRequest.serializeBinaryToWriter (/Users/nathan/google-assistant/lib/google/assistant/embedded/v1alpha1/embedded_assistant_pb.js:1417:12)

**Comment by endoplasmic** [comment]
The only thing I could suggest is downgrading your npm (I've had issues with 5 both at home and work).

`sudo npm install -g npm@3.10.10`

fwiw, I also created this on a mac, so I know it works with it :)

**Comment by sipvoip** [comment]
Odd, same results with 3.10.10.

**Comment by oroce** [comment]
The package.json says `google-protobuf@^3.3.0` and the latest version of it which 3.4.0 satisfies this condition. Probably there were some breaking changes between those versions because downgrading to 3.3.0 resolves the issue posted by @sipvoip.

**Comment by endoplasmic** [comment]
This is why open source software is rad.

Alright, so I've changed the package file to *not* grab the latest stuff from google until I can get some time to figure out what was changed.

I've also forked the `node-record-lpcm16` repo and added support for Windows users.

Try updating and let me know if you hit any snags.

**Comment by siuying** [comment]
Use 3.3.0 but no luck...

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn rec ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Gauss:test $ node -v
v8.9.1
Gauss:test $ npm -v
5.5.1
Gauss:test $ yarn -v
1.3.2
```
