### ISSUE TITLE
Error While Using README Code

### ISSUE THREAD

**Issue by navanchauhan** [endoplasmic/google-assistant#35]
When the README Code is used, it throws the following error:
```
module.js:557
    throw err;
    ^

Error: Cannot find module 'google-assistant'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/tmp/google-assistant/main.js:2:25)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by navanchauhan** [comment]
These are my previous commands :
```
$ git clone https://github.com/endoplasmic/google-assistant
$ cd google-assistant
$ npm install google-assistant
$ npm install grpc
$ npm install (The Speaker Dependency)
$ npm install
$ mv ~/google_oauth.json ./examples/YOUR_KEY_FILE.json
The created a js file named main.js with the readme code, accounting for json file
```

I am a total noob when it comes to anything except bash, C++ or Python :p

**Comment by endoplasmic** [comment]
You can use one of the examples and replace the ../index with
google-assistant

Should work :)

**Comment by navanchauhan** [comment]
The Examples are working fine btw

**Comment by endoplasmic** [comment]
Going to close this as it's pretty old and the readme code seems to work when copy/pasting it.
