### ISSUE TITLE
Error getting tokens

### ISSUE THREAD

**Issue by henryoliver** [endoplasmic/google-assistant#39]
Any help guys I would appreciate it! Thanks!

```/home/pi/google-assistant-nodejs/node_modules/google-assistant/components/auth.js:73
      if (error) throw new Error('Error getting tokens:', error);
                 ^

Error: Error getting tokens:
    at oauthClient.getToken (/home/pi/google-assistant-nodejs/node_modules/google-assistant/components/auth.js:73:24)
    at /home/pi/google-assistant-nodejs/node_modules/google-auth-library/lib/auth/oauth2client.js:154:5
    at Request._callback (/home/pi/google-assistant-nodejs/node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (/home/pi/google-assistant-nodejs/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/home/pi/google-assistant-nodejs/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
    at IncomingMessage.<anonymous> (/home/pi/google-assistant-nodejs/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:272:13)
    at IncomingMessage.emit (events.js:185:15)
```
```'use strict';

const record = require('node-record-lpcm16');
const Speaker = require('speaker');
const path = require('path');
const GoogleAssistant = require('google-assistant');
const speakerHelper = require('./speaker-helper');

const config = {
  auth: {
    keyFilePath: path.resolve(__dirname, '/home/pi/credentials.json'),
    savedTokensPath: path.resolve(__dirname, 'tokens.json'), // where you want the tokens to be saved
  },
  conversation: {
    audio: {
      sampleRateOut: 24000, // defaults to 24000
    },
    lang: 'en-US', // defaults to en-US, but try other ones, it's fun!
  },
};
```

**Comment by endoplasmic** [comment]
Couple of options:

1) Your `keyFilePath` is a little wacky. If you want to use an absolute path, you don't need to use the path module at all. Just set it as `/home/pi/credentials.json` and remove the `path.resolve` stuff.

2) Your credentials.json file isn't right, it should look something like this:

```json
{  
   "installed":{  
      "client_id":"xxxxxxx.apps.googleusercontent.com",
      "project_id":"xxxxxx",
      "auth_uri":"https://accounts.google.com/o/oauth2/auth",
      "token_uri":"https://accounts.google.com/o/oauth2/token",
      "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
      "client_secret":"xxxxxx",
      "redirect_uris":[  
         "urn:ietf:wg:oauth:2.0:oob",
         "http://localhost"
      ]
   }
}
```

**Comment by henryoliver** [comment]
Thank you @endoplasmic! Will test it tonight and let you know soon!

**Comment by henryoliver** [comment]
@endoplasmic worked! Thanks!
