### ISSUE TITLE
TypeError: callback is not a function (index.js)

### ISSUE THREAD

**Issue by E3V3A** [endoplasmic/google-assistant#41]
We're running the following code to get the tokens. It used to work...

```js
const config = {
    auth: {
        keyFilePath: path.resolve(__dirname,     '../assets/google-client-secret.json'), // secret.json
        savedTokensPath: path.resolve(__dirname, '../assets/google-access-tokens.json'), // resources/tokens.js
    },
}

//const assistant = new GoogleAssistant(config)
// Not sure if this additional parameter is needed...
const assistant = new GoogleAssistant(config.auth, "MagicMirror")
assistant
  .on('ready', () => {
    assistant.start();
  })
  .on('started', function() {
    console.log("Google Authentication OK! Press CTRL+C to Quit.")
  })
  .on('error', (error) => {
    console.log('Google Authentication Error:', error)
  })
```

But after pasting the token, we are now getting the following error:
```
Google Authentication OK! Press CTRL+C to Quit.
/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/index.js:26
    if (callback) callback(assistant);
                  ^

TypeError: callback is not a function
    at Auth.GoogleAssistant.auth.on (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/index.js:26:19)
    at Auth.emit (events.js:180:13)
    at saveTokens (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/components/auth.js:32:10)
    at oauthClient.getToken (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/components/auth.js:76:7)
    at /home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/node_modules/google-auth-library/lib/auth/oauth2client.js:154:5
    at Request._callback (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/google-assistant/node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Assistant/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)
```

Any ideas how to fix this?

**Comment by endoplasmic** [comment]
Where you have `"MagicMirror"` is actually a callback when the assistant is ready. Instead of passing a string, pass a function that will trigger when it's ready (it's the same as if you were using `.on('ready'`

**Comment by E3V3A** [comment]
So you're saying I could do something like this?
```js
const assistant = new GoogleAssistant(config.auth, function () {
    console.log("Authentication OK");
    process.exit(0);
})
...
```
Or how else could I exit nicely, when everything is ok?

**Comment by endoplasmic** [comment]
You can use your old code and just take out the "MagicMirror" part as well.

But what you proposed should work as well (kill the process when it's ready).

**Comment by E3V3A** [comment]
Super! Thanks a lot. I will try that. I tried to kill it elsewhere before, but then the file would not be written...
